// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: dashboard.proto

package dashboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dashboard_GetRSAPubKey_FullMethodName       = "/dashboard.Dashboard/GetRSAPubKey"
	Dashboard_Login_FullMethodName              = "/dashboard.Dashboard/Login"
	Dashboard_GetUserInfo_FullMethodName        = "/dashboard.Dashboard/GetUserInfo"
	Dashboard_DisabledRBAC_FullMethodName       = "/dashboard.Dashboard/DisabledRBAC"
	Dashboard_AuthUser_FullMethodName           = "/dashboard.Dashboard/AuthUser"
	Dashboard_ChangeUserPassword_FullMethodName = "/dashboard.Dashboard/ChangeUserPassword"
	Dashboard_ListMenuConf_FullMethodName       = "/dashboard.Dashboard/ListMenuConf"
	Dashboard_AddMenuConf_FullMethodName        = "/dashboard.Dashboard/AddMenuConf"
	Dashboard_UpdateMenuConf_FullMethodName     = "/dashboard.Dashboard/UpdateMenuConf"
	Dashboard_DeleteMenuConf_FullMethodName     = "/dashboard.Dashboard/DeleteMenuConf"
	Dashboard_ListRoleConf_FullMethodName       = "/dashboard.Dashboard/ListRoleConf"
	Dashboard_AddRoleConf_FullMethodName        = "/dashboard.Dashboard/AddRoleConf"
	Dashboard_UpdateRoleConf_FullMethodName     = "/dashboard.Dashboard/UpdateRoleConf"
	Dashboard_DeleteRoleConf_FullMethodName     = "/dashboard.Dashboard/DeleteRoleConf"
)

// DashboardClient is the client API for Dashboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardClient interface {
	GetRSAPubKey(ctx context.Context, in *GetRSAPubKeyReq, opts ...grpc.CallOption) (*GetRSAPubKeyResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	DisabledRBAC(ctx context.Context, in *DisabledRBACReq, opts ...grpc.CallOption) (*DisabledRBACResp, error)
	AuthUser(ctx context.Context, in *AuthUserReq, opts ...grpc.CallOption) (*AuthUserResp, error)
	ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordReq, opts ...grpc.CallOption) (*ChangeUserPasswordResp, error)
	ListMenuConf(ctx context.Context, in *ListMenuConfReq, opts ...grpc.CallOption) (*ListMenuConfResp, error)
	AddMenuConf(ctx context.Context, in *AddMenuConfReq, opts ...grpc.CallOption) (*AddMenuConfResp, error)
	UpdateMenuConf(ctx context.Context, in *UpdateMenuConfReq, opts ...grpc.CallOption) (*UpdateMenuConfResp, error)
	DeleteMenuConf(ctx context.Context, in *DeleteMenuConfReq, opts ...grpc.CallOption) (*DeleteMenuConfResp, error)
	ListRoleConf(ctx context.Context, in *ListRoleConfReq, opts ...grpc.CallOption) (*ListRoleConfResp, error)
	AddRoleConf(ctx context.Context, in *AddRoleConfReq, opts ...grpc.CallOption) (*AddRoleConfResp, error)
	UpdateRoleConf(ctx context.Context, in *UpdateRoleConfReq, opts ...grpc.CallOption) (*UpdateRoleConfResp, error)
	DeleteRoleConf(ctx context.Context, in *DeleteRoleConfReq, opts ...grpc.CallOption) (*DeleteRoleConfResp, error)
}

type dashboardClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardClient(cc grpc.ClientConnInterface) DashboardClient {
	return &dashboardClient{cc}
}

func (c *dashboardClient) GetRSAPubKey(ctx context.Context, in *GetRSAPubKeyReq, opts ...grpc.CallOption) (*GetRSAPubKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRSAPubKeyResp)
	err := c.cc.Invoke(ctx, Dashboard_GetRSAPubKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, Dashboard_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, Dashboard_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) DisabledRBAC(ctx context.Context, in *DisabledRBACReq, opts ...grpc.CallOption) (*DisabledRBACResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisabledRBACResp)
	err := c.cc.Invoke(ctx, Dashboard_DisabledRBAC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) AuthUser(ctx context.Context, in *AuthUserReq, opts ...grpc.CallOption) (*AuthUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUserResp)
	err := c.cc.Invoke(ctx, Dashboard_AuthUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordReq, opts ...grpc.CallOption) (*ChangeUserPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeUserPasswordResp)
	err := c.cc.Invoke(ctx, Dashboard_ChangeUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) ListMenuConf(ctx context.Context, in *ListMenuConfReq, opts ...grpc.CallOption) (*ListMenuConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMenuConfResp)
	err := c.cc.Invoke(ctx, Dashboard_ListMenuConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) AddMenuConf(ctx context.Context, in *AddMenuConfReq, opts ...grpc.CallOption) (*AddMenuConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMenuConfResp)
	err := c.cc.Invoke(ctx, Dashboard_AddMenuConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) UpdateMenuConf(ctx context.Context, in *UpdateMenuConfReq, opts ...grpc.CallOption) (*UpdateMenuConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMenuConfResp)
	err := c.cc.Invoke(ctx, Dashboard_UpdateMenuConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) DeleteMenuConf(ctx context.Context, in *DeleteMenuConfReq, opts ...grpc.CallOption) (*DeleteMenuConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMenuConfResp)
	err := c.cc.Invoke(ctx, Dashboard_DeleteMenuConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) ListRoleConf(ctx context.Context, in *ListRoleConfReq, opts ...grpc.CallOption) (*ListRoleConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleConfResp)
	err := c.cc.Invoke(ctx, Dashboard_ListRoleConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) AddRoleConf(ctx context.Context, in *AddRoleConfReq, opts ...grpc.CallOption) (*AddRoleConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRoleConfResp)
	err := c.cc.Invoke(ctx, Dashboard_AddRoleConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) UpdateRoleConf(ctx context.Context, in *UpdateRoleConfReq, opts ...grpc.CallOption) (*UpdateRoleConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleConfResp)
	err := c.cc.Invoke(ctx, Dashboard_UpdateRoleConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardClient) DeleteRoleConf(ctx context.Context, in *DeleteRoleConfReq, opts ...grpc.CallOption) (*DeleteRoleConfResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleConfResp)
	err := c.cc.Invoke(ctx, Dashboard_DeleteRoleConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServer is the server API for Dashboard service.
// All implementations must embed UnimplementedDashboardServer
// for forward compatibility.
type DashboardServer interface {
	GetRSAPubKey(context.Context, *GetRSAPubKeyReq) (*GetRSAPubKeyResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	DisabledRBAC(context.Context, *DisabledRBACReq) (*DisabledRBACResp, error)
	AuthUser(context.Context, *AuthUserReq) (*AuthUserResp, error)
	ChangeUserPassword(context.Context, *ChangeUserPasswordReq) (*ChangeUserPasswordResp, error)
	ListMenuConf(context.Context, *ListMenuConfReq) (*ListMenuConfResp, error)
	AddMenuConf(context.Context, *AddMenuConfReq) (*AddMenuConfResp, error)
	UpdateMenuConf(context.Context, *UpdateMenuConfReq) (*UpdateMenuConfResp, error)
	DeleteMenuConf(context.Context, *DeleteMenuConfReq) (*DeleteMenuConfResp, error)
	ListRoleConf(context.Context, *ListRoleConfReq) (*ListRoleConfResp, error)
	AddRoleConf(context.Context, *AddRoleConfReq) (*AddRoleConfResp, error)
	UpdateRoleConf(context.Context, *UpdateRoleConfReq) (*UpdateRoleConfResp, error)
	DeleteRoleConf(context.Context, *DeleteRoleConfReq) (*DeleteRoleConfResp, error)
	mustEmbedUnimplementedDashboardServer()
}

// UnimplementedDashboardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServer struct{}

func (UnimplementedDashboardServer) GetRSAPubKey(context.Context, *GetRSAPubKeyReq) (*GetRSAPubKeyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRSAPubKey not implemented")
}
func (UnimplementedDashboardServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDashboardServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedDashboardServer) DisabledRBAC(context.Context, *DisabledRBACReq) (*DisabledRBACResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisabledRBAC not implemented")
}
func (UnimplementedDashboardServer) AuthUser(context.Context, *AuthUserReq) (*AuthUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedDashboardServer) ChangeUserPassword(context.Context, *ChangeUserPasswordReq) (*ChangeUserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserPassword not implemented")
}
func (UnimplementedDashboardServer) ListMenuConf(context.Context, *ListMenuConfReq) (*ListMenuConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMenuConf not implemented")
}
func (UnimplementedDashboardServer) AddMenuConf(context.Context, *AddMenuConfReq) (*AddMenuConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMenuConf not implemented")
}
func (UnimplementedDashboardServer) UpdateMenuConf(context.Context, *UpdateMenuConfReq) (*UpdateMenuConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenuConf not implemented")
}
func (UnimplementedDashboardServer) DeleteMenuConf(context.Context, *DeleteMenuConfReq) (*DeleteMenuConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenuConf not implemented")
}
func (UnimplementedDashboardServer) ListRoleConf(context.Context, *ListRoleConfReq) (*ListRoleConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoleConf not implemented")
}
func (UnimplementedDashboardServer) AddRoleConf(context.Context, *AddRoleConfReq) (*AddRoleConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoleConf not implemented")
}
func (UnimplementedDashboardServer) UpdateRoleConf(context.Context, *UpdateRoleConfReq) (*UpdateRoleConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleConf not implemented")
}
func (UnimplementedDashboardServer) DeleteRoleConf(context.Context, *DeleteRoleConfReq) (*DeleteRoleConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoleConf not implemented")
}
func (UnimplementedDashboardServer) mustEmbedUnimplementedDashboardServer() {}
func (UnimplementedDashboardServer) testEmbeddedByValue()                   {}

// UnsafeDashboardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServer will
// result in compilation errors.
type UnsafeDashboardServer interface {
	mustEmbedUnimplementedDashboardServer()
}

func RegisterDashboardServer(s grpc.ServiceRegistrar, srv DashboardServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dashboard_ServiceDesc, srv)
}

func _Dashboard_GetRSAPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRSAPubKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).GetRSAPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_GetRSAPubKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).GetRSAPubKey(ctx, req.(*GetRSAPubKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_DisabledRBAC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisabledRBACReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).DisabledRBAC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_DisabledRBAC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).DisabledRBAC(ctx, req.(*DisabledRBACReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_AuthUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).AuthUser(ctx, req.(*AuthUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_ChangeUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).ChangeUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_ChangeUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).ChangeUserPassword(ctx, req.(*ChangeUserPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_ListMenuConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenuConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).ListMenuConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_ListMenuConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).ListMenuConf(ctx, req.(*ListMenuConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_AddMenuConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMenuConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).AddMenuConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_AddMenuConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).AddMenuConf(ctx, req.(*AddMenuConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_UpdateMenuConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).UpdateMenuConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_UpdateMenuConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).UpdateMenuConf(ctx, req.(*UpdateMenuConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_DeleteMenuConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).DeleteMenuConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_DeleteMenuConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).DeleteMenuConf(ctx, req.(*DeleteMenuConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_ListRoleConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).ListRoleConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_ListRoleConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).ListRoleConf(ctx, req.(*ListRoleConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_AddRoleConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).AddRoleConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_AddRoleConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).AddRoleConf(ctx, req.(*AddRoleConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_UpdateRoleConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).UpdateRoleConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_UpdateRoleConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).UpdateRoleConf(ctx, req.(*UpdateRoleConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dashboard_DeleteRoleConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServer).DeleteRoleConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dashboard_DeleteRoleConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServer).DeleteRoleConf(ctx, req.(*DeleteRoleConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Dashboard_ServiceDesc is the grpc.ServiceDesc for Dashboard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dashboard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.Dashboard",
	HandlerType: (*DashboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRSAPubKey",
			Handler:    _Dashboard_GetRSAPubKey_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Dashboard_Login_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Dashboard_GetUserInfo_Handler,
		},
		{
			MethodName: "DisabledRBAC",
			Handler:    _Dashboard_DisabledRBAC_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _Dashboard_AuthUser_Handler,
		},
		{
			MethodName: "ChangeUserPassword",
			Handler:    _Dashboard_ChangeUserPassword_Handler,
		},
		{
			MethodName: "ListMenuConf",
			Handler:    _Dashboard_ListMenuConf_Handler,
		},
		{
			MethodName: "AddMenuConf",
			Handler:    _Dashboard_AddMenuConf_Handler,
		},
		{
			MethodName: "UpdateMenuConf",
			Handler:    _Dashboard_UpdateMenuConf_Handler,
		},
		{
			MethodName: "DeleteMenuConf",
			Handler:    _Dashboard_DeleteMenuConf_Handler,
		},
		{
			MethodName: "ListRoleConf",
			Handler:    _Dashboard_ListRoleConf_Handler,
		},
		{
			MethodName: "AddRoleConf",
			Handler:    _Dashboard_AddRoleConf_Handler,
		},
		{
			MethodName: "UpdateRoleConf",
			Handler:    _Dashboard_UpdateRoleConf_Handler,
		},
		{
			MethodName: "DeleteRoleConf",
			Handler:    _Dashboard_DeleteRoleConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
