// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: dashboard.proto

package dashboard

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mconfigcenter-dashboard/backend/api/httpext"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil               ErrCode = 0
	ErrCode_ErrCodeRSAKeysGenerating ErrCode = 30001
	ErrCode_ErrCodeUserNotFound      ErrCode = 30002
	ErrCode_ErrCodePasswordIncorrect ErrCode = 30003
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "ErrCodeNil",
		30001: "ErrCodeRSAKeysGenerating",
		30002: "ErrCodeUserNotFound",
		30003: "ErrCodePasswordIncorrect",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":               0,
		"ErrCodeRSAKeysGenerating": 30001,
		"ErrCodeUserNotFound":      30002,
		"ErrCodePasswordIncorrect": 30003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_dashboard_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_dashboard_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_UserStatusNil    UserStatus = 0
	UserStatus_UserStatusNormal UserStatus = 1 // 正常状态
	UserStatus_UserStatusFrozen UserStatus = 2 // 冻结状态
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserStatusNil",
		1: "UserStatusNormal",
		2: "UserStatusFrozen",
	}
	UserStatus_value = map[string]int32{
		"UserStatusNil":    0,
		"UserStatusNormal": 1,
		"UserStatusFrozen": 2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dashboard_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_dashboard_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

type DeleteRoleConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleConfReq) Reset() {
	*x = DeleteRoleConfReq{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleConfReq) ProtoMessage() {}

func (x *DeleteRoleConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleConfReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRoleConfReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type DeleteRoleConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleConfResp) Reset() {
	*x = DeleteRoleConfResp{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleConfResp) ProtoMessage() {}

func (x *DeleteRoleConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleConfResp.ProtoReflect.Descriptor instead.
func (*DeleteRoleConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

type AddRoleConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	IsSuperAdmin  bool                   `protobuf:"varint,3,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	PermIds       []uint64               `protobuf:"varint,4,rep,packed,name=perm_ids,json=permIds,proto3" json:"perm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleConfReq) Reset() {
	*x = AddRoleConfReq{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleConfReq) ProtoMessage() {}

func (x *AddRoleConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleConfReq.ProtoReflect.Descriptor instead.
func (*AddRoleConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *AddRoleConfReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRoleConfReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddRoleConfReq) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *AddRoleConfReq) GetPermIds() []uint64 {
	if x != nil {
		return x.PermIds
	}
	return nil
}

type AddRoleConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleConfResp) Reset() {
	*x = AddRoleConfResp{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleConfResp) ProtoMessage() {}

func (x *AddRoleConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleConfResp.ProtoReflect.Descriptor instead.
func (*AddRoleConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

type UpdateRoleConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	IsSuperAdmin  bool                   `protobuf:"varint,4,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	PermIds       []uint64               `protobuf:"varint,5,rep,packed,name=perm_ids,json=permIds,proto3" json:"perm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleConfReq) Reset() {
	*x = UpdateRoleConfReq{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleConfReq) ProtoMessage() {}

func (x *UpdateRoleConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleConfReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoleConfReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UpdateRoleConfReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleConfReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateRoleConfReq) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *UpdateRoleConfReq) GetPermIds() []uint64 {
	if x != nil {
		return x.PermIds
	}
	return nil
}

type UpdateRoleConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleConfResp) Reset() {
	*x = UpdateRoleConfResp{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleConfResp) ProtoMessage() {}

func (x *UpdateRoleConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleConfResp.ProtoReflect.Descriptor instead.
func (*UpdateRoleConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

type ListRoleConfReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status            int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	OnlySuperAdmin    bool                   `protobuf:"varint,3,opt,name=only_super_admin,json=onlySuperAdmin,proto3" json:"only_super_admin,omitempty"`
	WithoutSuperAdmin bool                   `protobuf:"varint,4,opt,name=without_super_admin,json=withoutSuperAdmin,proto3" json:"without_super_admin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRoleConfReq) Reset() {
	*x = ListRoleConfReq{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleConfReq) ProtoMessage() {}

func (x *ListRoleConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleConfReq.ProtoReflect.Descriptor instead.
func (*ListRoleConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoleConfReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRoleConfReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListRoleConfReq) GetOnlySuperAdmin() bool {
	if x != nil {
		return x.OnlySuperAdmin
	}
	return false
}

func (x *ListRoleConfReq) GetWithoutSuperAdmin() bool {
	if x != nil {
		return x.WithoutSuperAdmin
	}
	return false
}

type ListRoleConfResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	List          []*ListRoleConfResp_Role `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleConfResp) Reset() {
	*x = ListRoleConfResp{}
	mi := &file_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleConfResp) ProtoMessage() {}

func (x *ListRoleConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleConfResp.ProtoReflect.Descriptor instead.
func (*ListRoleConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoleConfResp) GetList() []*ListRoleConfResp_Role {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleConfResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteMenuConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermId        uint64                 `protobuf:"varint,1,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuConfReq) Reset() {
	*x = DeleteMenuConfReq{}
	mi := &file_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuConfReq) ProtoMessage() {}

func (x *DeleteMenuConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuConfReq.ProtoReflect.Descriptor instead.
func (*DeleteMenuConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMenuConfReq) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

type DeleteMenuConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuConfResp) Reset() {
	*x = DeleteMenuConfResp{}
	mi := &file_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuConfResp) ProtoMessage() {}

func (x *DeleteMenuConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuConfResp.ProtoReflect.Descriptor instead.
func (*DeleteMenuConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

type UpdateMenuConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 权限名称
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Services      []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	Pid           uint64                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	PermId        uint64                 `protobuf:"varint,6,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	PathType      int32                  `protobuf:"varint,7,opt,name=path_type,json=pathType,proto3" json:"path_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuConfReq) Reset() {
	*x = UpdateMenuConfReq{}
	mi := &file_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuConfReq) ProtoMessage() {}

func (x *UpdateMenuConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuConfReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMenuConfReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuConfReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuConfReq) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *UpdateMenuConfReq) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdateMenuConfReq) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *UpdateMenuConfReq) GetPathType() int32 {
	if x != nil {
		return x.PathType
	}
	return 0
}

type UpdateMenuConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuConfResp) Reset() {
	*x = UpdateMenuConfResp{}
	mi := &file_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuConfResp) ProtoMessage() {}

func (x *UpdateMenuConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuConfResp.ProtoReflect.Descriptor instead.
func (*UpdateMenuConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{11}
}

type AddMenuConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 权限名称
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Services      []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	Pid           uint64                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	PathType      int32                  `protobuf:"varint,6,opt,name=path_type,json=pathType,proto3" json:"path_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuConfReq) Reset() {
	*x = AddMenuConfReq{}
	mi := &file_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuConfReq) ProtoMessage() {}

func (x *AddMenuConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuConfReq.ProtoReflect.Descriptor instead.
func (*AddMenuConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *AddMenuConfReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMenuConfReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddMenuConfReq) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AddMenuConfReq) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AddMenuConfReq) GetPathType() int32 {
	if x != nil {
		return x.PathType
	}
	return 0
}

type AddMenuConfResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMenuConfResp) Reset() {
	*x = AddMenuConfResp{}
	mi := &file_dashboard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMenuConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMenuConfResp) ProtoMessage() {}

func (x *AddMenuConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMenuConfResp.ProtoReflect.Descriptor instead.
func (*AddMenuConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{13}
}

type ListMenuConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuConfReq) Reset() {
	*x = ListMenuConfReq{}
	mi := &file_dashboard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuConfReq) ProtoMessage() {}

func (x *ListMenuConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuConfReq.ProtoReflect.Descriptor instead.
func (*ListMenuConfReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{14}
}

type ListMenuConfResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	List          []*ListMenuConfResp_MenuConf `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuConfResp) Reset() {
	*x = ListMenuConfResp{}
	mi := &file_dashboard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuConfResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuConfResp) ProtoMessage() {}

func (x *ListMenuConfResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuConfResp.ProtoReflect.Descriptor instead.
func (*ListMenuConfResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{15}
}

func (x *ListMenuConfResp) GetList() []*ListMenuConfResp_MenuConf {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMenuConfResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChangeUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPassword   string                 `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordReq) Reset() {
	*x = ChangeUserPasswordReq{}
	mi := &file_dashboard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordReq) ProtoMessage() {}

func (x *ChangeUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordReq.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeUserPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeUserPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordResp) Reset() {
	*x = ChangeUserPasswordResp{}
	mi := &file_dashboard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordResp) ProtoMessage() {}

func (x *ChangeUserPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordResp.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{17}
}

type AuthUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserReq) Reset() {
	*x = AuthUserReq{}
	mi := &file_dashboard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserReq) ProtoMessage() {}

func (x *AuthUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserReq.ProtoReflect.Descriptor instead.
func (*AuthUserReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{18}
}

func (x *AuthUserReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResp) Reset() {
	*x = AuthUserResp{}
	mi := &file_dashboard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResp) ProtoMessage() {}

func (x *AuthUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResp.ProtoReflect.Descriptor instead.
func (*AuthUserResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{19}
}

func (x *AuthUserResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DisabledRBACReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisabledRBACReq) Reset() {
	*x = DisabledRBACReq{}
	mi := &file_dashboard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisabledRBACReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabledRBACReq) ProtoMessage() {}

func (x *DisabledRBACReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabledRBACReq.ProtoReflect.Descriptor instead.
func (*DisabledRBACReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{20}
}

type DisabledRBACResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisabledRBACResp) Reset() {
	*x = DisabledRBACResp{}
	mi := &file_dashboard_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisabledRBACResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabledRBACResp) ProtoMessage() {}

func (x *DisabledRBACResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabledRBACResp.ProtoReflect.Descriptor instead.
func (*DisabledRBACResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{21}
}

func (x *DisabledRBACResp) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_dashboard_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{22}
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RoleNames     []string               `protobuf:"bytes,3,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	LastLoginAt   int64                  `protobuf:"varint,4,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_dashboard_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserInfoResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResp) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

func (x *GetUserInfoResp) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

type GetRSAPubKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRSAPubKeyReq) Reset() {
	*x = GetRSAPubKeyReq{}
	mi := &file_dashboard_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRSAPubKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRSAPubKeyReq) ProtoMessage() {}

func (x *GetRSAPubKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRSAPubKeyReq.ProtoReflect.Descriptor instead.
func (*GetRSAPubKeyReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{24}
}

type GetRSAPubKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRSAPubKeyResp) Reset() {
	*x = GetRSAPubKeyResp{}
	mi := &file_dashboard_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRSAPubKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRSAPubKeyResp) ProtoMessage() {}

func (x *GetRSAPubKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRSAPubKeyResp.ProtoReflect.Descriptor instead.
func (*GetRSAPubKeyResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{25}
}

func (x *GetRSAPubKeyResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_dashboard_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{26}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_dashboard_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{27}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastLoginAt   int64                  `protobuf:"varint,5,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_dashboard_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{28}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

type ListRoleConfResp_Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                     // 角色id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 角色名称
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态，参考enum RoleStatus
	PermIds       []uint64               `protobuf:"varint,4,rep,packed,name=perm_ids,json=permIds,proto3" json:"perm_ids,omitempty"`           // 权限id
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`                                    // 备注
	IsSuperAdmin  bool                   `protobuf:"varint,6,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"` // 是否超级管理员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleConfResp_Role) Reset() {
	*x = ListRoleConfResp_Role{}
	mi := &file_dashboard_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleConfResp_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleConfResp_Role) ProtoMessage() {}

func (x *ListRoleConfResp_Role) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleConfResp_Role.ProtoReflect.Descriptor instead.
func (*ListRoleConfResp_Role) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListRoleConfResp_Role) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ListRoleConfResp_Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRoleConfResp_Role) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListRoleConfResp_Role) GetPermIds() []uint64 {
	if x != nil {
		return x.PermIds
	}
	return nil
}

func (x *ListRoleConfResp_Role) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ListRoleConfResp_Role) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

type ListMenuConfResp_MenuConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermId        uint64                 `protobuf:"varint,1,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"` // 权限id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                    // 权限名称
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Services      []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	Pid           uint64                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	PathType      int32                  `protobuf:"varint,6,opt,name=path_type,json=pathType,proto3" json:"path_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuConfResp_MenuConf) Reset() {
	*x = ListMenuConfResp_MenuConf{}
	mi := &file_dashboard_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuConfResp_MenuConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuConfResp_MenuConf) ProtoMessage() {}

func (x *ListMenuConfResp_MenuConf) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuConfResp_MenuConf.ProtoReflect.Descriptor instead.
func (*ListMenuConfResp_MenuConf) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ListMenuConfResp_MenuConf) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *ListMenuConfResp_MenuConf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMenuConfResp_MenuConf) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListMenuConfResp_MenuConf) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListMenuConfResp_MenuConf) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListMenuConfResp_MenuConf) GetPathType() int32 {
	if x != nil {
		return x.PathType
	}
	return 0
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\tdashboard\x1a\x13easymicro_ext.proto\x1a\x0fmgorm_ext.proto\x1a\rhttpext.proto\",\n" +
	"\x11DeleteRoleConfReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\"\x14\n" +
	"\x12DeleteRoleConfResp\"}\n" +
	"\x0eAddRoleConfReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12$\n" +
	"\x0eis_super_admin\x18\x03 \x01(\bR\fisSuperAdmin\x12\x19\n" +
	"\bperm_ids\x18\x04 \x03(\x04R\apermIds\"\x11\n" +
	"\x0fAddRoleConfResp\"\x99\x01\n" +
	"\x11UpdateRoleConfReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12$\n" +
	"\x0eis_super_admin\x18\x04 \x01(\bR\fisSuperAdmin\x12\x19\n" +
	"\bperm_ids\x18\x05 \x03(\x04R\apermIds\"\x14\n" +
	"\x12UpdateRoleConfResp\"\x97\x01\n" +
	"\x0fListRoleConfReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12(\n" +
	"\x10only_super_admin\x18\x03 \x01(\bR\x0eonlySuperAdmin\x12.\n" +
	"\x13without_super_admin\x18\x04 \x01(\bR\x11withoutSuperAdmin\"\x85\x02\n" +
	"\x10ListRoleConfResp\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .dashboard.ListRoleConfResp.RoleR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x1a\xa4\x01\n" +
	"\x04Role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x19\n" +
	"\bperm_ids\x18\x04 \x03(\x04R\apermIds\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12$\n" +
	"\x0eis_super_admin\x18\x06 \x01(\bR\fisSuperAdmin\",\n" +
	"\x11DeleteMenuConfReq\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\x04R\x06permId\"\x14\n" +
	"\x12DeleteMenuConfResp\"\x9f\x01\n" +
	"\x11UpdateMenuConfReq\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x04R\x03pid\x12\x17\n" +
	"\aperm_id\x18\x06 \x01(\x04R\x06permId\x12\x1b\n" +
	"\tpath_type\x18\a \x01(\x05R\bpathType\"\x14\n" +
	"\x12UpdateMenuConfResp\"\x83\x01\n" +
	"\x0eAddMenuConfReq\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x04R\x03pid\x12\x1b\n" +
	"\tpath_type\x18\x06 \x01(\x05R\bpathType\"\x11\n" +
	"\x0fAddMenuConfResp\"\x11\n" +
	"\x0fListMenuConfReq\"\xfb\x01\n" +
	"\x10ListMenuConfResp\x128\n" +
	"\x04list\x18\x01 \x03(\v2$.dashboard.ListMenuConfResp.MenuConfR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x1a\x96\x01\n" +
	"\bMenuConf\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\x04R\x06permId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x04R\x03pid\x12\x1b\n" +
	"\tpath_type\x18\x06 \x01(\x05R\bpathType\":\n" +
	"\x15ChangeUserPasswordReq\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangeUserPasswordResp\"#\n" +
	"\vAuthUserReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\fAuthUserResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x11\n" +
	"\x0fDisabledRBACReq\".\n" +
	"\x10DisabledRBACResp\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"\x10\n" +
	"\x0eGetUserInfoReq\"\x89\x01\n" +
	"\x0fGetUserInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"role_names\x18\x03 \x03(\tR\troleNames\x12\"\n" +
	"\rlast_login_at\x18\x04 \x01(\x03R\vlastLoginAt\"\x11\n" +
	"\x0fGetRSAPubKeyReq\"$\n" +
	"\x10GetRSAPubKeyResp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"\xd6\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\"\n" +
	"\rlast_login_at\x18\x05 \x01(\x03R\vlastLoginAt:A\x8a\x8e%=\n" +
	"\adefault\x12\x17mconfigcenter_dashboard\x1a\x04user \x01:\busername:\auser_id*\xc0\x01\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12<\n" +
	"\x18ErrCodeRSAKeysGenerating\x10\xb1\xea\x01\x1a\x1c\x8a\x9d \x18\n" +
	"\x16rsa key正在生成中\x120\n" +
	"\x13ErrCodeUserNotFound\x10\xb2\xea\x01\x1a\x15\x8a\x9d \x11\n" +
	"\x0f用户不存在\x125\n" +
	"\x18ErrCodePasswordIncorrect\x10\xb3\xea\x01\x1a\x15\x8a\x9d \x11\n" +
	"\x0f密码不正确*K\n" +
	"\n" +
	"UserStatus\x12\x11\n" +
	"\rUserStatusNil\x10\x00\x12\x14\n" +
	"\x10UserStatusNormal\x10\x01\x12\x14\n" +
	"\x10UserStatusFrozen\x10\x022\xa5\t\n" +
	"\tDashboard\x12U\n" +
	"\fGetRSAPubKey\x12\x1a.dashboard.GetRSAPubKeyReq\x1a\x1b.dashboard.GetRSAPubKeyResp\"\f\xca\xf3\x18\b\n" +
	"\x04POST\x18\x01\x12@\n" +
	"\x05Login\x12\x13.dashboard.LoginReq\x1a\x14.dashboard.LoginResp\"\f\xca\xf3\x18\b\n" +
	"\x04POST\x18\x01\x12O\n" +
	"\vGetUserInfo\x12\x19.dashboard.GetUserInfoReq\x1a\x1a.dashboard.GetUserInfoResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12R\n" +
	"\fDisabledRBAC\x12\x1a.dashboard.DisabledRBACReq\x1a\x1b.dashboard.DisabledRBACResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12;\n" +
	"\bAuthUser\x12\x16.dashboard.AuthUserReq\x1a\x17.dashboard.AuthUserResp\x12e\n" +
	"\x12ChangeUserPassword\x12 .dashboard.ChangeUserPasswordReq\x1a!.dashboard.ChangeUserPasswordResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12R\n" +
	"\fListMenuConf\x12\x1a.dashboard.ListMenuConfReq\x1a\x1b.dashboard.ListMenuConfResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12P\n" +
	"\vAddMenuConf\x12\x19.dashboard.AddMenuConfReq\x1a\x1a.dashboard.AddMenuConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12Y\n" +
	"\x0eUpdateMenuConf\x12\x1c.dashboard.UpdateMenuConfReq\x1a\x1d.dashboard.UpdateMenuConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12Y\n" +
	"\x0eDeleteMenuConf\x12\x1c.dashboard.DeleteMenuConfReq\x1a\x1d.dashboard.DeleteMenuConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12R\n" +
	"\fListRoleConf\x12\x1a.dashboard.ListRoleConfReq\x1a\x1b.dashboard.ListRoleConfResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12P\n" +
	"\vAddRoleConf\x12\x19.dashboard.AddRoleConfReq\x1a\x1a.dashboard.AddRoleConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12Y\n" +
	"\x0eUpdateRoleConf\x12\x1c.dashboard.UpdateRoleConfReq\x1a\x1d.dashboard.UpdateRoleConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POST\x12Y\n" +
	"\x0eDeleteRoleConf\x12\x1c.dashboard.DeleteRoleConfReq\x1a\x1d.dashboard.DeleteRoleConfResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POSTB\x96\x01\x8a\x9d N\n" +
	"Lgithub.com/995933447/mconfigcenter-dashboard/backend/service/dashboardserverZBgithub.com/995933447/mconfigcenter-dashboard/backend/api/dashboardb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_dashboard_proto_goTypes = []any{
	(ErrCode)(0),                      // 0: dashboard.ErrCode
	(UserStatus)(0),                   // 1: dashboard.UserStatus
	(*DeleteRoleConfReq)(nil),         // 2: dashboard.DeleteRoleConfReq
	(*DeleteRoleConfResp)(nil),        // 3: dashboard.DeleteRoleConfResp
	(*AddRoleConfReq)(nil),            // 4: dashboard.AddRoleConfReq
	(*AddRoleConfResp)(nil),           // 5: dashboard.AddRoleConfResp
	(*UpdateRoleConfReq)(nil),         // 6: dashboard.UpdateRoleConfReq
	(*UpdateRoleConfResp)(nil),        // 7: dashboard.UpdateRoleConfResp
	(*ListRoleConfReq)(nil),           // 8: dashboard.ListRoleConfReq
	(*ListRoleConfResp)(nil),          // 9: dashboard.ListRoleConfResp
	(*DeleteMenuConfReq)(nil),         // 10: dashboard.DeleteMenuConfReq
	(*DeleteMenuConfResp)(nil),        // 11: dashboard.DeleteMenuConfResp
	(*UpdateMenuConfReq)(nil),         // 12: dashboard.UpdateMenuConfReq
	(*UpdateMenuConfResp)(nil),        // 13: dashboard.UpdateMenuConfResp
	(*AddMenuConfReq)(nil),            // 14: dashboard.AddMenuConfReq
	(*AddMenuConfResp)(nil),           // 15: dashboard.AddMenuConfResp
	(*ListMenuConfReq)(nil),           // 16: dashboard.ListMenuConfReq
	(*ListMenuConfResp)(nil),          // 17: dashboard.ListMenuConfResp
	(*ChangeUserPasswordReq)(nil),     // 18: dashboard.ChangeUserPasswordReq
	(*ChangeUserPasswordResp)(nil),    // 19: dashboard.ChangeUserPasswordResp
	(*AuthUserReq)(nil),               // 20: dashboard.AuthUserReq
	(*AuthUserResp)(nil),              // 21: dashboard.AuthUserResp
	(*DisabledRBACReq)(nil),           // 22: dashboard.DisabledRBACReq
	(*DisabledRBACResp)(nil),          // 23: dashboard.DisabledRBACResp
	(*GetUserInfoReq)(nil),            // 24: dashboard.GetUserInfoReq
	(*GetUserInfoResp)(nil),           // 25: dashboard.GetUserInfoResp
	(*GetRSAPubKeyReq)(nil),           // 26: dashboard.GetRSAPubKeyReq
	(*GetRSAPubKeyResp)(nil),          // 27: dashboard.GetRSAPubKeyResp
	(*LoginReq)(nil),                  // 28: dashboard.LoginReq
	(*LoginResp)(nil),                 // 29: dashboard.LoginResp
	(*User)(nil),                      // 30: dashboard.User
	(*ListRoleConfResp_Role)(nil),     // 31: dashboard.ListRoleConfResp.Role
	(*ListMenuConfResp_MenuConf)(nil), // 32: dashboard.ListMenuConfResp.MenuConf
}
var file_dashboard_proto_depIdxs = []int32{
	31, // 0: dashboard.ListRoleConfResp.list:type_name -> dashboard.ListRoleConfResp.Role
	32, // 1: dashboard.ListMenuConfResp.list:type_name -> dashboard.ListMenuConfResp.MenuConf
	26, // 2: dashboard.Dashboard.GetRSAPubKey:input_type -> dashboard.GetRSAPubKeyReq
	28, // 3: dashboard.Dashboard.Login:input_type -> dashboard.LoginReq
	24, // 4: dashboard.Dashboard.GetUserInfo:input_type -> dashboard.GetUserInfoReq
	22, // 5: dashboard.Dashboard.DisabledRBAC:input_type -> dashboard.DisabledRBACReq
	20, // 6: dashboard.Dashboard.AuthUser:input_type -> dashboard.AuthUserReq
	18, // 7: dashboard.Dashboard.ChangeUserPassword:input_type -> dashboard.ChangeUserPasswordReq
	16, // 8: dashboard.Dashboard.ListMenuConf:input_type -> dashboard.ListMenuConfReq
	14, // 9: dashboard.Dashboard.AddMenuConf:input_type -> dashboard.AddMenuConfReq
	12, // 10: dashboard.Dashboard.UpdateMenuConf:input_type -> dashboard.UpdateMenuConfReq
	10, // 11: dashboard.Dashboard.DeleteMenuConf:input_type -> dashboard.DeleteMenuConfReq
	8,  // 12: dashboard.Dashboard.ListRoleConf:input_type -> dashboard.ListRoleConfReq
	4,  // 13: dashboard.Dashboard.AddRoleConf:input_type -> dashboard.AddRoleConfReq
	6,  // 14: dashboard.Dashboard.UpdateRoleConf:input_type -> dashboard.UpdateRoleConfReq
	2,  // 15: dashboard.Dashboard.DeleteRoleConf:input_type -> dashboard.DeleteRoleConfReq
	27, // 16: dashboard.Dashboard.GetRSAPubKey:output_type -> dashboard.GetRSAPubKeyResp
	29, // 17: dashboard.Dashboard.Login:output_type -> dashboard.LoginResp
	25, // 18: dashboard.Dashboard.GetUserInfo:output_type -> dashboard.GetUserInfoResp
	23, // 19: dashboard.Dashboard.DisabledRBAC:output_type -> dashboard.DisabledRBACResp
	21, // 20: dashboard.Dashboard.AuthUser:output_type -> dashboard.AuthUserResp
	19, // 21: dashboard.Dashboard.ChangeUserPassword:output_type -> dashboard.ChangeUserPasswordResp
	17, // 22: dashboard.Dashboard.ListMenuConf:output_type -> dashboard.ListMenuConfResp
	15, // 23: dashboard.Dashboard.AddMenuConf:output_type -> dashboard.AddMenuConfResp
	13, // 24: dashboard.Dashboard.UpdateMenuConf:output_type -> dashboard.UpdateMenuConfResp
	11, // 25: dashboard.Dashboard.DeleteMenuConf:output_type -> dashboard.DeleteMenuConfResp
	9,  // 26: dashboard.Dashboard.ListRoleConf:output_type -> dashboard.ListRoleConfResp
	5,  // 27: dashboard.Dashboard.AddRoleConf:output_type -> dashboard.AddRoleConfResp
	7,  // 28: dashboard.Dashboard.UpdateRoleConf:output_type -> dashboard.UpdateRoleConfResp
	3,  // 29: dashboard.Dashboard.DeleteRoleConf:output_type -> dashboard.DeleteRoleConfResp
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		EnumInfos:         file_dashboard_proto_enumTypes,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
