// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package dashboard

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "easymicro"
	EasymicroDiscoveryName = "default"
)

const EasymicroGRPCPbServiceNameDashboard = "dashboard.Dashboard"

var DashboardDefault = &Dashboard{}

func DashboardGRPC() *Dashboard {
	return DashboardDefault
}

func NewDashboardGRPC(dialOpts ...grpc.DialOption) *Dashboard {
	return &Dashboard{
		dialOpts: dialOpts,
	}
}

type Dashboard struct {
	c        DashboardClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *Dashboard) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *Dashboard) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameDashboard)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameDashboard, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewDashboardClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *Dashboard) GetRSAPubKey(ctx context.Context, in *GetRSAPubKeyReq, opts ...grpc.CallOption) (*GetRSAPubKeyResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetRSAPubKey(ctx, in, opts...)
}

func (s *Dashboard) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.Login(ctx, in, opts...)
}

func (s *Dashboard) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.GetUserInfo(ctx, in, opts...)
}

func (s *Dashboard) DisabledRBAC(ctx context.Context, in *DisabledRBACReq, opts ...grpc.CallOption) (*DisabledRBACResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DisabledRBAC(ctx, in, opts...)
}

func (s *Dashboard) AuthUser(ctx context.Context, in *AuthUserReq, opts ...grpc.CallOption) (*AuthUserResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AuthUser(ctx, in, opts...)
}

func (s *Dashboard) ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordReq, opts ...grpc.CallOption) (*ChangeUserPasswordResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ChangeUserPassword(ctx, in, opts...)
}

func (s *Dashboard) ListMenuConf(ctx context.Context, in *ListMenuConfReq, opts ...grpc.CallOption) (*ListMenuConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListMenuConf(ctx, in, opts...)
}

func (s *Dashboard) AddMenuConf(ctx context.Context, in *AddMenuConfReq, opts ...grpc.CallOption) (*AddMenuConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddMenuConf(ctx, in, opts...)
}

func (s *Dashboard) UpdateMenuConf(ctx context.Context, in *UpdateMenuConfReq, opts ...grpc.CallOption) (*UpdateMenuConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateMenuConf(ctx, in, opts...)
}

func (s *Dashboard) DeleteMenuConf(ctx context.Context, in *DeleteMenuConfReq, opts ...grpc.CallOption) (*DeleteMenuConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteMenuConf(ctx, in, opts...)
}

func (s *Dashboard) ListRoleConf(ctx context.Context, in *ListRoleConfReq, opts ...grpc.CallOption) (*ListRoleConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListRoleConf(ctx, in, opts...)
}

func (s *Dashboard) AddRoleConf(ctx context.Context, in *AddRoleConfReq, opts ...grpc.CallOption) (*AddRoleConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddRoleConf(ctx, in, opts...)
}

func (s *Dashboard) UpdateRoleConf(ctx context.Context, in *UpdateRoleConfReq, opts ...grpc.CallOption) (*UpdateRoleConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateRoleConf(ctx, in, opts...)
}

func (s *Dashboard) DeleteRoleConf(ctx context.Context, in *DeleteRoleConfReq, opts ...grpc.CallOption) (*DeleteRoleConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteRoleConf(ctx, in, opts...)
}

func (s *Dashboard) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListUser(ctx, in, opts...)
}

func (s *Dashboard) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddUser(ctx, in, opts...)
}

func (s *Dashboard) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateUser(ctx, in, opts...)
}

func (s *Dashboard) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteUser(ctx, in, opts...)
}

func (s *Dashboard) ListGeneralConf(ctx context.Context, in *ListGeneralConfReq, opts ...grpc.CallOption) (*ListGeneralConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListGeneralConf(ctx, in, opts...)
}

func (s *Dashboard) ListConfSchema(ctx context.Context, in *ListConfSchemaReq, opts ...grpc.CallOption) (*ListConfSchemaResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListConfSchema(ctx, in, opts...)
}

func (s *Dashboard) SetConfigSchema(ctx context.Context, in *SetConfSchemaReq, opts ...grpc.CallOption) (*SetConfSchemaResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetConfigSchema(ctx, in, opts...)
}

func (s *Dashboard) AddGeneralConf(ctx context.Context, in *AddGeneralConfReq, opts ...grpc.CallOption) (*AddGeneralConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AddGeneralConf(ctx, in, opts...)
}

func (s *Dashboard) UpdateGeneralConf(ctx context.Context, in *UpdateGeneralConfReq, opts ...grpc.CallOption) (*UpdateGeneralConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.UpdateGeneralConf(ctx, in, opts...)
}

func (s *Dashboard) DeleteGeneralConf(ctx context.Context, in *DeleteGeneralConfReq, opts ...grpc.CallOption) (*DeleteGeneralConfResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.DeleteGeneralConf(ctx, in, opts...)
}

func (s *Dashboard) ListUserPerm(ctx context.Context, in *ListUserPermReq, opts ...grpc.CallOption) (*ListUserPermResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListUserPerm(ctx, in, opts...)
}
