// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: dashboard.proto

package dashboard

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mconfigcenter-dashboard/backend/api/httpext"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil               ErrCode = 0
	ErrCode_ErrCodeRSAKeysGenerating ErrCode = 30001
	ErrCode_ErrCodeUserNotFound      ErrCode = 30002
	ErrCode_ErrCodePasswordIncorrect ErrCode = 30003
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "ErrCodeNil",
		30001: "ErrCodeRSAKeysGenerating",
		30002: "ErrCodeUserNotFound",
		30003: "ErrCodePasswordIncorrect",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":               0,
		"ErrCodeRSAKeysGenerating": 30001,
		"ErrCodeUserNotFound":      30002,
		"ErrCodePasswordIncorrect": 30003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_dashboard_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_dashboard_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_UserStatusNil    UserStatus = 0
	UserStatus_UserStatusNormal UserStatus = 1 // 正常状态
	UserStatus_UserStatusFrozen UserStatus = 2 // 冻结状态
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserStatusNil",
		1: "UserStatusNormal",
		2: "UserStatusFrozen",
	}
	UserStatus_value = map[string]int32{
		"UserStatusNil":    0,
		"UserStatusNormal": 1,
		"UserStatusFrozen": 2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dashboard_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_dashboard_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

type ChangeUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPassword   string                 `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordReq) Reset() {
	*x = ChangeUserPasswordReq{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordReq) ProtoMessage() {}

func (x *ChangeUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordReq.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeUserPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeUserPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserPasswordResp) Reset() {
	*x = ChangeUserPasswordResp{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserPasswordResp) ProtoMessage() {}

func (x *ChangeUserPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserPasswordResp.ProtoReflect.Descriptor instead.
func (*ChangeUserPasswordResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

type AuthUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserReq) Reset() {
	*x = AuthUserReq{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserReq) ProtoMessage() {}

func (x *AuthUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserReq.ProtoReflect.Descriptor instead.
func (*AuthUserReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResp) Reset() {
	*x = AuthUserResp{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResp) ProtoMessage() {}

func (x *AuthUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResp.ProtoReflect.Descriptor instead.
func (*AuthUserResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *AuthUserResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DisabledRBACReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisabledRBACReq) Reset() {
	*x = DisabledRBACReq{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisabledRBACReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabledRBACReq) ProtoMessage() {}

func (x *DisabledRBACReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabledRBACReq.ProtoReflect.Descriptor instead.
func (*DisabledRBACReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

type DisabledRBACResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisabledRBACResp) Reset() {
	*x = DisabledRBACResp{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisabledRBACResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabledRBACResp) ProtoMessage() {}

func (x *DisabledRBACResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabledRBACResp.ProtoReflect.Descriptor instead.
func (*DisabledRBACResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *DisabledRBACResp) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RoleNames     []string               `protobuf:"bytes,3,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	LastLoginAt   int64                  `protobuf:"varint,4,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResp) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

func (x *GetUserInfoResp) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

type GetRSAPubKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRSAPubKeyReq) Reset() {
	*x = GetRSAPubKeyReq{}
	mi := &file_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRSAPubKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRSAPubKeyReq) ProtoMessage() {}

func (x *GetRSAPubKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRSAPubKeyReq.ProtoReflect.Descriptor instead.
func (*GetRSAPubKeyReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

type GetRSAPubKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRSAPubKeyResp) Reset() {
	*x = GetRSAPubKeyResp{}
	mi := &file_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRSAPubKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRSAPubKeyResp) ProtoMessage() {}

func (x *GetRSAPubKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRSAPubKeyResp.ProtoReflect.Descriptor instead.
func (*GetRSAPubKeyResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *GetRSAPubKeyResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastLoginAt   int64                  `protobuf:"varint,5,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\tdashboard\x1a\x13easymicro_ext.proto\x1a\x0fmgorm_ext.proto\x1a\rhttpext.proto\":\n" +
	"\x15ChangeUserPasswordReq\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangeUserPasswordResp\"#\n" +
	"\vAuthUserReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\fAuthUserResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x11\n" +
	"\x0fDisabledRBACReq\".\n" +
	"\x10DisabledRBACResp\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"\x10\n" +
	"\x0eGetUserInfoReq\"\x89\x01\n" +
	"\x0fGetUserInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"role_names\x18\x03 \x03(\tR\troleNames\x12\"\n" +
	"\rlast_login_at\x18\x04 \x01(\x03R\vlastLoginAt\"\x11\n" +
	"\x0fGetRSAPubKeyReq\"$\n" +
	"\x10GetRSAPubKeyResp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"\xd6\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\"\n" +
	"\rlast_login_at\x18\x05 \x01(\x03R\vlastLoginAt:A\x8a\x8e%=\n" +
	"\adefault\x12\x17mconfigcenter_dashboard\x1a\x04user \x01:\busername:\auser_id*\xc0\x01\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12<\n" +
	"\x18ErrCodeRSAKeysGenerating\x10\xb1\xea\x01\x1a\x1c\x8a\x9d \x18\n" +
	"\x16rsa key正在生成中\x120\n" +
	"\x13ErrCodeUserNotFound\x10\xb2\xea\x01\x1a\x15\x8a\x9d \x11\n" +
	"\x0f用户不存在\x125\n" +
	"\x18ErrCodePasswordIncorrect\x10\xb3\xea\x01\x1a\x15\x8a\x9d \x11\n" +
	"\x0f密码不正确*K\n" +
	"\n" +
	"UserStatus\x12\x11\n" +
	"\rUserStatusNil\x10\x00\x12\x14\n" +
	"\x10UserStatusNormal\x10\x01\x12\x14\n" +
	"\x10UserStatusFrozen\x10\x022\xed\x03\n" +
	"\tDashboard\x12U\n" +
	"\fGetRSAPubKey\x12\x1a.dashboard.GetRSAPubKeyReq\x1a\x1b.dashboard.GetRSAPubKeyResp\"\f\xca\xf3\x18\b\n" +
	"\x04POST\x18\x01\x12@\n" +
	"\x05Login\x12\x13.dashboard.LoginReq\x1a\x14.dashboard.LoginResp\"\f\xca\xf3\x18\b\n" +
	"\x04POST\x18\x01\x12O\n" +
	"\vGetUserInfo\x12\x19.dashboard.GetUserInfoReq\x1a\x1a.dashboard.GetUserInfoResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12R\n" +
	"\fDisabledRBAC\x12\x1a.dashboard.DisabledRBACReq\x1a\x1b.dashboard.DisabledRBACResp\"\t\xca\xf3\x18\x05\n" +
	"\x03GET\x12;\n" +
	"\bAuthUser\x12\x16.dashboard.AuthUserReq\x1a\x17.dashboard.AuthUserResp\x12e\n" +
	"\x12ChangeUserPassword\x12 .dashboard.ChangeUserPasswordReq\x1a!.dashboard.ChangeUserPasswordResp\"\n" +
	"\xca\xf3\x18\x06\n" +
	"\x04POSTB\x96\x01\x8a\x9d N\n" +
	"Lgithub.com/995933447/mconfigcenter-dashboard/backend/service/dashboardserverZBgithub.com/995933447/mconfigcenter-dashboard/backend/api/dashboardb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dashboard_proto_goTypes = []any{
	(ErrCode)(0),                   // 0: dashboard.ErrCode
	(UserStatus)(0),                // 1: dashboard.UserStatus
	(*ChangeUserPasswordReq)(nil),  // 2: dashboard.ChangeUserPasswordReq
	(*ChangeUserPasswordResp)(nil), // 3: dashboard.ChangeUserPasswordResp
	(*AuthUserReq)(nil),            // 4: dashboard.AuthUserReq
	(*AuthUserResp)(nil),           // 5: dashboard.AuthUserResp
	(*DisabledRBACReq)(nil),        // 6: dashboard.DisabledRBACReq
	(*DisabledRBACResp)(nil),       // 7: dashboard.DisabledRBACResp
	(*GetUserInfoReq)(nil),         // 8: dashboard.GetUserInfoReq
	(*GetUserInfoResp)(nil),        // 9: dashboard.GetUserInfoResp
	(*GetRSAPubKeyReq)(nil),        // 10: dashboard.GetRSAPubKeyReq
	(*GetRSAPubKeyResp)(nil),       // 11: dashboard.GetRSAPubKeyResp
	(*LoginReq)(nil),               // 12: dashboard.LoginReq
	(*LoginResp)(nil),              // 13: dashboard.LoginResp
	(*User)(nil),                   // 14: dashboard.User
}
var file_dashboard_proto_depIdxs = []int32{
	10, // 0: dashboard.Dashboard.GetRSAPubKey:input_type -> dashboard.GetRSAPubKeyReq
	12, // 1: dashboard.Dashboard.Login:input_type -> dashboard.LoginReq
	8,  // 2: dashboard.Dashboard.GetUserInfo:input_type -> dashboard.GetUserInfoReq
	6,  // 3: dashboard.Dashboard.DisabledRBAC:input_type -> dashboard.DisabledRBACReq
	4,  // 4: dashboard.Dashboard.AuthUser:input_type -> dashboard.AuthUserReq
	2,  // 5: dashboard.Dashboard.ChangeUserPassword:input_type -> dashboard.ChangeUserPasswordReq
	11, // 6: dashboard.Dashboard.GetRSAPubKey:output_type -> dashboard.GetRSAPubKeyResp
	13, // 7: dashboard.Dashboard.Login:output_type -> dashboard.LoginResp
	9,  // 8: dashboard.Dashboard.GetUserInfo:output_type -> dashboard.GetUserInfoResp
	7,  // 9: dashboard.Dashboard.DisabledRBAC:output_type -> dashboard.DisabledRBACResp
	5,  // 10: dashboard.Dashboard.AuthUser:output_type -> dashboard.AuthUserResp
	3,  // 11: dashboard.Dashboard.ChangeUserPassword:output_type -> dashboard.ChangeUserPasswordResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		EnumInfos:         file_dashboard_proto_enumTypes,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
