// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/mconfigcenter-dashboard/backend/api/dashboard"
	"github.com/995933447/mconfigcenter-dashboard/backend/service/dashboardserver/handler"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "GetRSAPubKey", handler.DashboardHandler.GetRSAPubKey, func() *dashboard.GetRSAPubKeyReq {
		return &dashboard.GetRSAPubKeyReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "Login", handler.DashboardHandler.Login, func() *dashboard.LoginReq {
		return &dashboard.LoginReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "GetUserInfo", handler.DashboardHandler.GetUserInfo, func() *dashboard.GetUserInfoReq {
		return &dashboard.GetUserInfoReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "DisabledRBAC", handler.DashboardHandler.DisabledRBAC, func() *dashboard.DisabledRBACReq {
		return &dashboard.DisabledRBACReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "AuthUser", handler.DashboardHandler.AuthUser, func() *dashboard.AuthUserReq {
		return &dashboard.AuthUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ChangeUserPassword", handler.DashboardHandler.ChangeUserPassword, func() *dashboard.ChangeUserPasswordReq {
		return &dashboard.ChangeUserPasswordReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
