// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/mconfigcenter-dashboard/backend/api/dashboard"
	"github.com/995933447/mconfigcenter-dashboard/backend/service/dashboardserver/handler"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "GetRSAPubKey", handler.DashboardHandler.GetRSAPubKey, func() *dashboard.GetRSAPubKeyReq {
		return &dashboard.GetRSAPubKeyReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "Login", handler.DashboardHandler.Login, func() *dashboard.LoginReq {
		return &dashboard.LoginReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "GetUserInfo", handler.DashboardHandler.GetUserInfo, func() *dashboard.GetUserInfoReq {
		return &dashboard.GetUserInfoReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "DisabledRBAC", handler.DashboardHandler.DisabledRBAC, func() *dashboard.DisabledRBACReq {
		return &dashboard.DisabledRBACReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "AuthUser", handler.DashboardHandler.AuthUser, func() *dashboard.AuthUserReq {
		return &dashboard.AuthUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ChangeUserPassword", handler.DashboardHandler.ChangeUserPassword, func() *dashboard.ChangeUserPasswordReq {
		return &dashboard.ChangeUserPasswordReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ListMenuConf", handler.DashboardHandler.ListMenuConf, func() *dashboard.ListMenuConfReq {
		return &dashboard.ListMenuConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "AddMenuConf", handler.DashboardHandler.AddMenuConf, func() *dashboard.AddMenuConfReq {
		return &dashboard.AddMenuConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "UpdateMenuConf", handler.DashboardHandler.UpdateMenuConf, func() *dashboard.UpdateMenuConfReq {
		return &dashboard.UpdateMenuConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "DeleteMenuConf", handler.DashboardHandler.DeleteMenuConf, func() *dashboard.DeleteMenuConfReq {
		return &dashboard.DeleteMenuConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ListRoleConf", handler.DashboardHandler.ListRoleConf, func() *dashboard.ListRoleConfReq {
		return &dashboard.ListRoleConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "AddRoleConf", handler.DashboardHandler.AddRoleConf, func() *dashboard.AddRoleConfReq {
		return &dashboard.AddRoleConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "UpdateRoleConf", handler.DashboardHandler.UpdateRoleConf, func() *dashboard.UpdateRoleConfReq {
		return &dashboard.UpdateRoleConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "DeleteRoleConf", handler.DashboardHandler.DeleteRoleConf, func() *dashboard.DeleteRoleConfReq {
		return &dashboard.DeleteRoleConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ListUser", handler.DashboardHandler.ListUser, func() *dashboard.ListUserReq {
		return &dashboard.ListUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "AddUser", handler.DashboardHandler.AddUser, func() *dashboard.AddUserReq {
		return &dashboard.AddUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "UpdateUser", handler.DashboardHandler.UpdateUser, func() *dashboard.UpdateUserReq {
		return &dashboard.UpdateUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "DeleteUser", handler.DashboardHandler.DeleteUser, func() *dashboard.DeleteUserReq {
		return &dashboard.DeleteUserReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ListGeneralConf", handler.DashboardHandler.ListGeneralConf, func() *dashboard.ListGeneralConfReq {
		return &dashboard.ListGeneralConfReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "ListConfSchema", handler.DashboardHandler.ListConfSchema, func() *dashboard.ListConfSchemaReq {
		return &dashboard.ListConfSchemaReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(dashboard.EasymicroGRPCPbServiceNameDashboard, "SetConfigSchema", handler.DashboardHandler.SetConfigSchema, func() *dashboard.SetConfSchemaReq {
		return &dashboard.SetConfSchemaReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
