// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/mconfigcenter-dashboard/backend/api/dashboard"
	"github.com/995933447/mconfigcenter-dashboard/backend/service/dashboardserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	dashboard.EasymicroGRPCPbServiceNameDashboard,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	dashboard.RegisterDashboardServer(server, handler.DashboardHandler)
	return nil
}
