// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: httpext.proto

package httpext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                       // GET, POST, etc.
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                           // URL path
	NoAuth        bool                   `protobuf:"varint,3,opt,name=no_auth,json=noAuth,proto3" json:"no_auth,omitempty"`                        // 是否跳过认证
	SkipPermCheck bool                   `protobuf:"varint,4,opt,name=skip_perm_check,json=skipPermCheck,proto3" json:"skip_perm_check,omitempty"` // 是否跳过访问权限检查
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRule) Reset() {
	*x = HttpRule{}
	mi := &file_httpext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRule) ProtoMessage() {}

func (x *HttpRule) ProtoReflect() protoreflect.Message {
	mi := &file_httpext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRule.ProtoReflect.Descriptor instead.
func (*HttpRule) Descriptor() ([]byte, []int) {
	return file_httpext_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRule) GetNoAuth() bool {
	if x != nil {
		return x.NoAuth
	}
	return false
}

func (x *HttpRule) GetSkipPermCheck() bool {
	if x != nil {
		return x.SkipPermCheck
	}
	return false
}

var file_httpext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         51001,
		Name:          "httpext.http_rule",
		Tag:           "bytes,51001,opt,name=http_rule",
		Filename:      "httpext.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional httpext.HttpRule http_rule = 51001;
	E_HttpRule = &file_httpext_proto_extTypes[0] // 定义http访问规则
)

var File_httpext_proto protoreflect.FileDescriptor

const file_httpext_proto_rawDesc = "" +
	"\n" +
	"\rhttpext.proto\x12\ahttpext\x1a google/protobuf/descriptor.proto\"w\n" +
	"\bHttpRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\ano_auth\x18\x03 \x01(\bR\x06noAuth\x12&\n" +
	"\x0fskip_perm_check\x18\x04 \x01(\bR\rskipPermCheck:P\n" +
	"\thttp_rule\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\v2\x11.httpext.HttpRuleR\bhttpRuleBBZ@github.com/995933447/mconfigcenter-dashboard/backend/api/httpextb\x06proto3"

var (
	file_httpext_proto_rawDescOnce sync.Once
	file_httpext_proto_rawDescData []byte
)

func file_httpext_proto_rawDescGZIP() []byte {
	file_httpext_proto_rawDescOnce.Do(func() {
		file_httpext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_httpext_proto_rawDesc), len(file_httpext_proto_rawDesc)))
	})
	return file_httpext_proto_rawDescData
}

var file_httpext_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_httpext_proto_goTypes = []any{
	(*HttpRule)(nil),                   // 0: httpext.HttpRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_httpext_proto_depIdxs = []int32{
	1, // 0: httpext.http_rule:extendee -> google.protobuf.MethodOptions
	0, // 1: httpext.http_rule:type_name -> httpext.HttpRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpext_proto_init() }
func file_httpext_proto_init() {
	if File_httpext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpext_proto_rawDesc), len(file_httpext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_httpext_proto_goTypes,
		DependencyIndexes: file_httpext_proto_depIdxs,
		MessageInfos:      file_httpext_proto_msgTypes,
		ExtensionInfos:    file_httpext_proto_extTypes,
	}.Build()
	File_httpext_proto = out.File
	file_httpext_proto_goTypes = nil
	file_httpext_proto_depIdxs = nil
}
