// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/mconfigcenter-dashboard/backend/api/gateway"
	"github.com/995933447/mconfigcenter-dashboard/backend/service/gatewayserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	gateway.EasymicroGRPCPbServiceNameGateway,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	gateway.RegisterGatewayServer(server, handler.GatewayHandler)
	return nil
}
