// Code generated by protoc-gen-easymicro-jsonschema. DO NOT EDIT.
package main

import (
	"fmt"
	"log"

	"github.com/995933447/mconfigcenter-dashboard/backend/api/dashboard"
	"github.com/995933447/runtimeutil"
	"github.com/invopop/jsonschema"
	jsoniter "github.com/json-iterator/go"
)

type ConfigSchemaOutput struct {
	Table         string             `json:"table"`
	IndexKeys     []string           `json:"index_keys"`
	UniqIndexKeys []string           `json:"uniq_index_keys"`
	JsonSchema    *jsonschema.Schema `json:"json_schema"`
	Desc          string             `json:"desc"`
}

func main() {
	jsonSchema := getJsonSchema()
	configSchemaOutput := &ConfigSchemaOutput{
		Table:     dashboard.ListenerGroupTbName,
		IndexKeys: []string{},
		UniqIndexKeys: []string{
			"name",
		},
		JsonSchema: jsonSchema,
		Desc:       "订阅服务组别",
	}
	s, err := jsoniter.MarshalToString(configSchemaOutput)
	if err != nil {
		log.Fatal(runtimeutil.NewStackErr(err))
	}
	fmt.Print(s)
}

func getJsonSchema() *jsonschema.Schema {
	r := &jsonschema.Reflector{}
	r.DoNotReference = true
	r.AllowAdditionalProperties = true
	r.RequiredFromJSONSchemaTags = true
	r.FieldNameTag = "bson"
	return r.Reflect(&dashboard.ListenerGroupOrm{})
}
