// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: commonerr.proto

package commonerr

import (
	_ "github.com/995933447/easymicro/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil          ErrCode = 0
	ErrCode_ErrCodeNoAuth       ErrCode = 20001
	ErrCode_ErrCodeInvalidParam ErrCode = 20002
	ErrCode_ErrCodeInternal     ErrCode = 20003
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "ErrCodeNil",
		20001: "ErrCodeNoAuth",
		20002: "ErrCodeInvalidParam",
		20003: "ErrCodeInternal",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":          0,
		"ErrCodeNoAuth":       20001,
		"ErrCodeInvalidParam": 20002,
		"ErrCodeInternal":     20003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_commonerr_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_commonerr_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_commonerr_proto_rawDescGZIP(), []int{0}
}

var File_commonerr_proto protoreflect.FileDescriptor

const file_commonerr_proto_rawDesc = "" +
	"\n" +
	"\x0fcommonerr.proto\x12\tcommonerr\x1a\x13easymicro_ext.proto*\x9f\x01\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12*\n" +
	"\rErrCodeNoAuth\x10\xa1\x9c\x01\x1a\x15\x8a\x9d \x11\n" +
	"\x0f请重新登录\x12-\n" +
	"\x13ErrCodeInvalidParam\x10\xa2\x9c\x01\x1a\x12\x8a\x9d \x0e\n" +
	"\f参数错误\x12)\n" +
	"\x0fErrCodeInternal\x10\xa3\x9c\x01\x1a\x12\x8a\x9d \x0e\n" +
	"\f系统错误BDZBgithub.com/995933447/mconfigcenter-dashboard/backend/api/commonerrb\x06proto3"

var (
	file_commonerr_proto_rawDescOnce sync.Once
	file_commonerr_proto_rawDescData []byte
)

func file_commonerr_proto_rawDescGZIP() []byte {
	file_commonerr_proto_rawDescOnce.Do(func() {
		file_commonerr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonerr_proto_rawDesc), len(file_commonerr_proto_rawDesc)))
	})
	return file_commonerr_proto_rawDescData
}

var file_commonerr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonerr_proto_goTypes = []any{
	(ErrCode)(0), // 0: commonerr.ErrCode
}
var file_commonerr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonerr_proto_init() }
func file_commonerr_proto_init() {
	if File_commonerr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonerr_proto_rawDesc), len(file_commonerr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonerr_proto_goTypes,
		DependencyIndexes: file_commonerr_proto_depIdxs,
		EnumInfos:         file_commonerr_proto_enumTypes,
	}.Build()
	File_commonerr_proto = out.File
	file_commonerr_proto_goTypes = nil
	file_commonerr_proto_depIdxs = nil
}
