// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package gateway

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = ""
	EasymicroDiscoveryName = ""
)

const EasymicroGRPCPbServiceNameGateway = "gateway.Gateway"

var GatewayDefault = &Gateway{}

func GatewayGRPC() *Gateway {
	return GatewayDefault
}

func NewGatewayGRPC(dialOpts ...grpc.DialOption) *Gateway {
	return &Gateway{
		dialOpts: dialOpts,
	}
}

type Gateway struct {
	c        GatewayClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *Gateway) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *Gateway) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameGateway)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameGateway, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewGatewayClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}
